"""Inicializar tablas de Swimmers

Revision ID: f4d0d0158c76
Revises: 
Create Date: 2025-12-09 00:04:16.545120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4d0d0158c76'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('horario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.String(length=15), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('nivel', sa.String(length=20), nullable=False),
    sa.Column('capacidad_maxima', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('membresia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('clases_por_semana', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('socio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folio', sa.String(length=20), nullable=True),
    sa.Column('nombre_completo', sa.String(length=100), nullable=False),
    sa.Column('foto', sa.String(length=200), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('nivel', sa.String(length=20), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('membresia_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['membresia_id'], ['membresia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('socio', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_socio_folio'), ['folio'], unique=True)

    op.create_table('tarifa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('membresia_id', sa.Integer(), nullable=False),
    sa.Column('nivel', sa.String(length=20), nullable=False),
    sa.Column('costo_mensual', sa.Float(), nullable=False),
    sa.Column('costo_anualidad', sa.Float(), nullable=False),
    sa.Column('costo_inscripcion', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['membresia_id'], ['membresia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asistencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('socio_id', sa.Integer(), nullable=False),
    sa.Column('horario_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['horario_id'], ['horario.id'], ),
    sa.ForeignKeyConstraint(['socio_id'], ['socio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inscripcion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('socio_id', sa.Integer(), nullable=False),
    sa.Column('horario_id', sa.Integer(), nullable=False),
    sa.Column('fecha_alta', sa.DateTime(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['horario_id'], ['horario.id'], ),
    sa.ForeignKeyConstraint(['socio_id'], ['socio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folio_recibo', sa.String(length=20), nullable=True),
    sa.Column('socio_id', sa.Integer(), nullable=False),
    sa.Column('fecha_pago', sa.DateTime(), nullable=True),
    sa.Column('concepto_tipo', sa.String(length=50), nullable=True),
    sa.Column('detalle_concepto', sa.String(length=100), nullable=True),
    sa.Column('monto_base', sa.Float(), nullable=True),
    sa.Column('monto_ajuste', sa.Float(), nullable=True),
    sa.Column('total_cobrado', sa.Float(), nullable=True),
    sa.Column('metodo_pago', sa.String(length=50), nullable=True),
    sa.Column('requiere_factura', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['socio_id'], ['socio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pago')
    op.drop_table('inscripcion')
    op.drop_table('asistencia')
    op.drop_table('tarifa')
    with op.batch_alter_table('socio', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_socio_folio'))

    op.drop_table('socio')
    op.drop_table('membresia')
    op.drop_table('horario')
    # ### end Alembic commands ###
